// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: rosina.proto

package valvedprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Duration uint64 `protobuf:"varint,1,opt,name=Duration,proto3" json:"Duration,omitempty"`
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosina_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rosina_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_rosina_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type OpenReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpenReply) Reset() {
	*x = OpenReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rosina_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenReply) ProtoMessage() {}

func (x *OpenReply) ProtoReflect() protoreflect.Message {
	mi := &file_rosina_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenReply.ProtoReflect.Descriptor instead.
func (*OpenReply) Descriptor() ([]byte, []int) {
	return file_rosina_proto_rawDescGZIP(), []int{1}
}

var File_rosina_proto protoreflect.FileDescriptor

var file_rosina_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x6f, 0x73, 0x69, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x22, 0x29, 0x0a, 0x0b, 0x4f, 0x70,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0b, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0x45, 0x0a, 0x09, 0x52, 0x6f, 0x73, 0x69, 0x6e, 0x61, 0x53, 0x76, 0x63, 0x12,
	0x38, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x17, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70,
	0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x48, 0x03, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x61, 0x72, 0x69,
	0x6f, 0x77, 0x2f, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x69, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rosina_proto_rawDescOnce sync.Once
	file_rosina_proto_rawDescData = file_rosina_proto_rawDesc
)

func file_rosina_proto_rawDescGZIP() []byte {
	file_rosina_proto_rawDescOnce.Do(func() {
		file_rosina_proto_rawDescData = protoimpl.X.CompressGZIP(file_rosina_proto_rawDescData)
	})
	return file_rosina_proto_rawDescData
}

var file_rosina_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rosina_proto_goTypes = []interface{}{
	(*OpenRequest)(nil), // 0: valvedgrpc.OpenRequest
	(*OpenReply)(nil),   // 1: valvedgrpc.OpenReply
}
var file_rosina_proto_depIdxs = []int32{
	0, // 0: valvedgrpc.RosinaSvc.Open:input_type -> valvedgrpc.OpenRequest
	1, // 1: valvedgrpc.RosinaSvc.Open:output_type -> valvedgrpc.OpenReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rosina_proto_init() }
func file_rosina_proto_init() {
	if File_rosina_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rosina_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rosina_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rosina_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rosina_proto_goTypes,
		DependencyIndexes: file_rosina_proto_depIdxs,
		MessageInfos:      file_rosina_proto_msgTypes,
	}.Build()
	File_rosina_proto = out.File
	file_rosina_proto_rawDesc = nil
	file_rosina_proto_goTypes = nil
	file_rosina_proto_depIdxs = nil
}
