// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package valvedprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RosinaSvcClient is the client API for RosinaSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RosinaSvcClient interface {
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenReply, error)
}

type rosinaSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewRosinaSvcClient(cc grpc.ClientConnInterface) RosinaSvcClient {
	return &rosinaSvcClient{cc}
}

func (c *rosinaSvcClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenReply, error) {
	out := new(OpenReply)
	err := c.cc.Invoke(ctx, "/valvedgrpc.RosinaSvc/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RosinaSvcServer is the server API for RosinaSvc service.
// All implementations must embed UnimplementedRosinaSvcServer
// for forward compatibility
type RosinaSvcServer interface {
	Open(context.Context, *OpenRequest) (*OpenReply, error)
	mustEmbedUnimplementedRosinaSvcServer()
}

// UnimplementedRosinaSvcServer must be embedded to have forward compatible implementations.
type UnimplementedRosinaSvcServer struct {
}

func (UnimplementedRosinaSvcServer) Open(context.Context, *OpenRequest) (*OpenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedRosinaSvcServer) mustEmbedUnimplementedRosinaSvcServer() {}

// UnsafeRosinaSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RosinaSvcServer will
// result in compilation errors.
type UnsafeRosinaSvcServer interface {
	mustEmbedUnimplementedRosinaSvcServer()
}

func RegisterRosinaSvcServer(s grpc.ServiceRegistrar, srv RosinaSvcServer) {
	s.RegisterService(&RosinaSvc_ServiceDesc, srv)
}

func _RosinaSvc_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RosinaSvcServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/valvedgrpc.RosinaSvc/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RosinaSvcServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RosinaSvc_ServiceDesc is the grpc.ServiceDesc for RosinaSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RosinaSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "valvedgrpc.RosinaSvc",
	HandlerType: (*RosinaSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _RosinaSvc_Open_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rosina.proto",
}
