// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: skedule.proto

package valvedprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddSkeduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skedule *Skedule `protobuf:"bytes,1,opt,name=Skedule,proto3" json:"Skedule,omitempty"`
}

func (x *AddSkeduleRequest) Reset() {
	*x = AddSkeduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSkeduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSkeduleRequest) ProtoMessage() {}

func (x *AddSkeduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSkeduleRequest.ProtoReflect.Descriptor instead.
func (*AddSkeduleRequest) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{0}
}

func (x *AddSkeduleRequest) GetSkedule() *Skedule {
	if x != nil {
		return x.Skedule
	}
	return nil
}

type AddSkeduleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *AddSkeduleReply) Reset() {
	*x = AddSkeduleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSkeduleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSkeduleReply) ProtoMessage() {}

func (x *AddSkeduleReply) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSkeduleReply.ProtoReflect.Descriptor instead.
func (*AddSkeduleReply) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{1}
}

func (x *AddSkeduleReply) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type ListSkedulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSkedulesRequest) Reset() {
	*x = ListSkedulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkedulesRequest) ProtoMessage() {}

func (x *ListSkedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSkedulesRequest) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{2}
}

type ListSkedulesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skedules []*Skedule `protobuf:"bytes,1,rep,name=Skedules,proto3" json:"Skedules,omitempty"`
}

func (x *ListSkedulesReply) Reset() {
	*x = ListSkedulesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSkedulesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkedulesReply) ProtoMessage() {}

func (x *ListSkedulesReply) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkedulesReply.ProtoReflect.Descriptor instead.
func (*ListSkedulesReply) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{3}
}

func (x *ListSkedulesReply) GetSkedules() []*Skedule {
	if x != nil {
		return x.Skedules
	}
	return nil
}

type GetSkeduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *GetSkeduleRequest) Reset() {
	*x = GetSkeduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSkeduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkeduleRequest) ProtoMessage() {}

func (x *GetSkeduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkeduleRequest.ProtoReflect.Descriptor instead.
func (*GetSkeduleRequest) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{4}
}

func (x *GetSkeduleRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type GetSkeduleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skedule *Skedule `protobuf:"bytes,1,opt,name=Skedule,proto3" json:"Skedule,omitempty"`
}

func (x *GetSkeduleReply) Reset() {
	*x = GetSkeduleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSkeduleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkeduleReply) ProtoMessage() {}

func (x *GetSkeduleReply) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkeduleReply.ProtoReflect.Descriptor instead.
func (*GetSkeduleReply) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{5}
}

func (x *GetSkeduleReply) GetSkedule() *Skedule {
	if x != nil {
		return x.Skedule
	}
	return nil
}

type DeleteSkeduleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
}

func (x *DeleteSkeduleRequest) Reset() {
	*x = DeleteSkeduleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSkeduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkeduleRequest) ProtoMessage() {}

func (x *DeleteSkeduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkeduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteSkeduleRequest) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSkeduleRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type DeleteSkeduleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSkeduleReply) Reset() {
	*x = DeleteSkeduleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSkeduleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSkeduleReply) ProtoMessage() {}

func (x *DeleteSkeduleReply) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSkeduleReply.ProtoReflect.Descriptor instead.
func (*DeleteSkeduleReply) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{7}
}

type Skedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName     string `protobuf:"bytes,1,opt,name=JobName,proto3" json:"JobName,omitempty"`
	CronSkedule string `protobuf:"bytes,2,opt,name=CronSkedule,proto3" json:"CronSkedule,omitempty"`
	DurationSec int64  `protobuf:"varint,3,opt,name=DurationSec,proto3" json:"DurationSec,omitempty"`
}

func (x *Skedule) Reset() {
	*x = Skedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_skedule_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skedule) ProtoMessage() {}

func (x *Skedule) ProtoReflect() protoreflect.Message {
	mi := &file_skedule_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skedule.ProtoReflect.Descriptor instead.
func (*Skedule) Descriptor() ([]byte, []int) {
	return file_skedule_proto_rawDescGZIP(), []int{8}
}

func (x *Skedule) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Skedule) GetCronSkedule() string {
	if x != nil {
		return x.CronSkedule
	}
	return ""
}

func (x *Skedule) GetDurationSec() int64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

var File_skedule_proto protoreflect.FileDescriptor

var file_skedule_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x22, 0x42, 0x0a, 0x11, 0x41,
	0x64, 0x64, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x07, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x22,
	0x2b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x08, 0x53, 0x6b, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76, 0x61, 0x6c,
	0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x08, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53,
	0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2d, 0x0a, 0x07, 0x53,
	0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x76,
	0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x52, 0x07, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x67, 0x0a, 0x07, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x6f, 0x6e, 0x53,
	0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x72,
	0x6f, 0x6e, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x32, 0xcb, 0x02, 0x0a, 0x0a,
	0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x76, 0x63, 0x12, 0x4a, 0x0a, 0x0a, 0x41, 0x64,
	0x64, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65,
	0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53,
	0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6b, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x48, 0x03, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x61, 0x72, 0x69,
	0x6f, 0x77, 0x2f, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x69, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_skedule_proto_rawDescOnce sync.Once
	file_skedule_proto_rawDescData = file_skedule_proto_rawDesc
)

func file_skedule_proto_rawDescGZIP() []byte {
	file_skedule_proto_rawDescOnce.Do(func() {
		file_skedule_proto_rawDescData = protoimpl.X.CompressGZIP(file_skedule_proto_rawDescData)
	})
	return file_skedule_proto_rawDescData
}

var file_skedule_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_skedule_proto_goTypes = []interface{}{
	(*AddSkeduleRequest)(nil),    // 0: valvedgrpc.AddSkeduleRequest
	(*AddSkeduleReply)(nil),      // 1: valvedgrpc.AddSkeduleReply
	(*ListSkedulesRequest)(nil),  // 2: valvedgrpc.ListSkedulesRequest
	(*ListSkedulesReply)(nil),    // 3: valvedgrpc.ListSkedulesReply
	(*GetSkeduleRequest)(nil),    // 4: valvedgrpc.GetSkeduleRequest
	(*GetSkeduleReply)(nil),      // 5: valvedgrpc.GetSkeduleReply
	(*DeleteSkeduleRequest)(nil), // 6: valvedgrpc.DeleteSkeduleRequest
	(*DeleteSkeduleReply)(nil),   // 7: valvedgrpc.DeleteSkeduleReply
	(*Skedule)(nil),              // 8: valvedgrpc.Skedule
}
var file_skedule_proto_depIdxs = []int32{
	8, // 0: valvedgrpc.AddSkeduleRequest.Skedule:type_name -> valvedgrpc.Skedule
	8, // 1: valvedgrpc.ListSkedulesReply.Skedules:type_name -> valvedgrpc.Skedule
	8, // 2: valvedgrpc.GetSkeduleReply.Skedule:type_name -> valvedgrpc.Skedule
	0, // 3: valvedgrpc.SkeduleSvc.AddSkedule:input_type -> valvedgrpc.AddSkeduleRequest
	2, // 4: valvedgrpc.SkeduleSvc.ListSkedules:input_type -> valvedgrpc.ListSkedulesRequest
	4, // 5: valvedgrpc.SkeduleSvc.GetSkedule:input_type -> valvedgrpc.GetSkeduleRequest
	6, // 6: valvedgrpc.SkeduleSvc.DeleteSkedule:input_type -> valvedgrpc.DeleteSkeduleRequest
	1, // 7: valvedgrpc.SkeduleSvc.AddSkedule:output_type -> valvedgrpc.AddSkeduleReply
	3, // 8: valvedgrpc.SkeduleSvc.ListSkedules:output_type -> valvedgrpc.ListSkedulesReply
	5, // 9: valvedgrpc.SkeduleSvc.GetSkedule:output_type -> valvedgrpc.GetSkeduleReply
	7, // 10: valvedgrpc.SkeduleSvc.DeleteSkedule:output_type -> valvedgrpc.DeleteSkeduleReply
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_skedule_proto_init() }
func file_skedule_proto_init() {
	if File_skedule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_skedule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSkeduleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSkeduleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkedulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSkedulesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSkeduleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSkeduleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSkeduleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSkeduleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_skedule_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_skedule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skedule_proto_goTypes,
		DependencyIndexes: file_skedule_proto_depIdxs,
		MessageInfos:      file_skedule_proto_msgTypes,
	}.Build()
	File_skedule_proto = out.File
	file_skedule_proto_rawDesc = nil
	file_skedule_proto_goTypes = nil
	file_skedule_proto_depIdxs = nil
}
