// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: valved.proto

package valvedprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValveStatus int32

const (
	ValveStatus_Open    ValveStatus = 0
	ValveStatus_Close   ValveStatus = 1
	ValveStatus_Invalid ValveStatus = 2
)

// Enum value maps for ValveStatus.
var (
	ValveStatus_name = map[int32]string{
		0: "Open",
		1: "Close",
		2: "Invalid",
	}
	ValveStatus_value = map[string]int32{
		"Open":    0,
		"Close":   1,
		"Invalid": 2,
	}
)

func (x ValveStatus) Enum() *ValveStatus {
	p := new(ValveStatus)
	*p = x
	return p
}

func (x ValveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_valved_proto_enumTypes[0].Descriptor()
}

func (ValveStatus) Type() protoreflect.EnumType {
	return &file_valved_proto_enumTypes[0]
}

func (x ValveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValveStatus.Descriptor instead.
func (ValveStatus) EnumDescriptor() ([]byte, []int) {
	return file_valved_proto_rawDescGZIP(), []int{0}
}

type OpenValveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpenValveRequest) Reset() {
	*x = OpenValveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valved_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenValveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenValveRequest) ProtoMessage() {}

func (x *OpenValveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valved_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenValveRequest.ProtoReflect.Descriptor instead.
func (*OpenValveRequest) Descriptor() ([]byte, []int) {
	return file_valved_proto_rawDescGZIP(), []int{0}
}

type OpenValveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *OpenValveReply) Reset() {
	*x = OpenValveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valved_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenValveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenValveReply) ProtoMessage() {}

func (x *OpenValveReply) ProtoReflect() protoreflect.Message {
	mi := &file_valved_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenValveReply.ProtoReflect.Descriptor instead.
func (*OpenValveReply) Descriptor() ([]byte, []int) {
	return file_valved_proto_rawDescGZIP(), []int{1}
}

func (x *OpenValveReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CloseValveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseValveRequest) Reset() {
	*x = CloseValveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valved_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseValveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseValveRequest) ProtoMessage() {}

func (x *CloseValveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valved_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseValveRequest.ProtoReflect.Descriptor instead.
func (*CloseValveRequest) Descriptor() ([]byte, []int) {
	return file_valved_proto_rawDescGZIP(), []int{2}
}

type CloseValveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *CloseValveReply) Reset() {
	*x = CloseValveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valved_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseValveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseValveReply) ProtoMessage() {}

func (x *CloseValveReply) ProtoReflect() protoreflect.Message {
	mi := &file_valved_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseValveReply.ProtoReflect.Descriptor instead.
func (*CloseValveReply) Descriptor() ([]byte, []int) {
	return file_valved_proto_rawDescGZIP(), []int{3}
}

func (x *CloseValveReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusValveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusValveRequest) Reset() {
	*x = StatusValveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valved_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusValveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusValveRequest) ProtoMessage() {}

func (x *StatusValveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_valved_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusValveRequest.ProtoReflect.Descriptor instead.
func (*StatusValveRequest) Descriptor() ([]byte, []int) {
	return file_valved_proto_rawDescGZIP(), []int{4}
}

type StatusValveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ValveStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=valvedgrpc.ValveStatus" json:"Status,omitempty"`
}

func (x *StatusValveReply) Reset() {
	*x = StatusValveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_valved_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusValveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusValveReply) ProtoMessage() {}

func (x *StatusValveReply) ProtoReflect() protoreflect.Message {
	mi := &file_valved_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusValveReply.ProtoReflect.Descriptor instead.
func (*StatusValveReply) Descriptor() ([]byte, []int) {
	return file_valved_proto_rawDescGZIP(), []int{5}
}

func (x *StatusValveReply) GetStatus() ValveStatus {
	if x != nil {
		return x.Status
	}
	return ValveStatus_Open
}

var File_valved_proto protoreflect.FileDescriptor

var file_valved_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x22, 0x12, 0x0a, 0x10, 0x4f, 0x70,
	0x65, 0x6e, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a,
	0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x2b, 0x0a, 0x0f, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x43, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x56, 0x61, 0x6c, 0x76,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x2f, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x76, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x02, 0x32, 0xe0, 0x01, 0x0a, 0x09, 0x56, 0x61, 0x6c,
	0x76, 0x65, 0x64, 0x53, 0x76, 0x63, 0x12, 0x42, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x1c,
	0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x6e,
	0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76,
	0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x56, 0x61,
	0x6c, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x05, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x12, 0x1d, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x76, 0x61,
	0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x56,
	0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x61,
	0x6c, 0x76, 0x65, 0x64, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x56,
	0x61, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x48, 0x03, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x6c, 0x61,
	0x72, 0x69, 0x6f, 0x77, 0x2f, 0x67, 0x61, 0x72, 0x64, 0x65, 0x6e, 0x69, 0x61, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x76, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_valved_proto_rawDescOnce sync.Once
	file_valved_proto_rawDescData = file_valved_proto_rawDesc
)

func file_valved_proto_rawDescGZIP() []byte {
	file_valved_proto_rawDescOnce.Do(func() {
		file_valved_proto_rawDescData = protoimpl.X.CompressGZIP(file_valved_proto_rawDescData)
	})
	return file_valved_proto_rawDescData
}

var file_valved_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_valved_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_valved_proto_goTypes = []interface{}{
	(ValveStatus)(0),           // 0: valvedgrpc.ValveStatus
	(*OpenValveRequest)(nil),   // 1: valvedgrpc.OpenValveRequest
	(*OpenValveReply)(nil),     // 2: valvedgrpc.OpenValveReply
	(*CloseValveRequest)(nil),  // 3: valvedgrpc.CloseValveRequest
	(*CloseValveReply)(nil),    // 4: valvedgrpc.CloseValveReply
	(*StatusValveRequest)(nil), // 5: valvedgrpc.StatusValveRequest
	(*StatusValveReply)(nil),   // 6: valvedgrpc.StatusValveReply
}
var file_valved_proto_depIdxs = []int32{
	0, // 0: valvedgrpc.StatusValveReply.Status:type_name -> valvedgrpc.ValveStatus
	1, // 1: valvedgrpc.ValvedSvc.Open:input_type -> valvedgrpc.OpenValveRequest
	3, // 2: valvedgrpc.ValvedSvc.Close:input_type -> valvedgrpc.CloseValveRequest
	5, // 3: valvedgrpc.ValvedSvc.Status:input_type -> valvedgrpc.StatusValveRequest
	2, // 4: valvedgrpc.ValvedSvc.Open:output_type -> valvedgrpc.OpenValveReply
	4, // 5: valvedgrpc.ValvedSvc.Close:output_type -> valvedgrpc.CloseValveReply
	6, // 6: valvedgrpc.ValvedSvc.Status:output_type -> valvedgrpc.StatusValveReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_valved_proto_init() }
func file_valved_proto_init() {
	if File_valved_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_valved_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenValveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valved_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenValveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valved_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseValveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valved_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseValveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valved_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusValveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_valved_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusValveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_valved_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_valved_proto_goTypes,
		DependencyIndexes: file_valved_proto_depIdxs,
		EnumInfos:         file_valved_proto_enumTypes,
		MessageInfos:      file_valved_proto_msgTypes,
	}.Build()
	File_valved_proto = out.File
	file_valved_proto_rawDesc = nil
	file_valved_proto_goTypes = nil
	file_valved_proto_depIdxs = nil
}
