apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: rosina
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
---
apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogInZhbHZlZCIKICBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6IFsiMTkyLjE2OC4xNzguMTk3OjIxMTIiXQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
