apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  namespace: rosina
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  retention: 90d
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
---
apiVersion: v1
stringData:
  prometheus-additional.yaml: |
    - job_name: "flowmeter"
      static_configs:
      - targets: ["192.168.178.197:12113"]
    - job_name: "valved"
      static_configs:
      - targets: ["192.168.178.197:2112"]
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: rosina
