apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rosinabot
  name: rosinabot
  namespace: rosina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosinabot
  strategy: {}
  template:
    metadata:
      labels:
        app: rosinabot
    spec:
      containers:
      - image: rosina/bot:latest
        name: bot
        imagePullPolicy: IfNotPresent
        resources: {}
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: rosinabot-token
              key: token
        - name: "SKEDULER_ADDRESS"
          value: "skeduler.rosina.svc.cluster.local:12000"
        - name: "PROMETHEUS_ADDRESS"
          value: "http://prometheus-operated.rosina.svc.cluster.local:9090"
        - name: "VALVED_ADDRESS"
          value: "192.168.1.21:12001"
        - name: "ROSINA_ADDRESS"
          value: "192.168.1.21:12000"
